import { beforeEach, describe, expect, it, vi } from 'vitest'
import { JSDOM } from 'jsdom'
import { crearPantallaAyuda, filtrarPreguntas, PREGUNTAS_AYUDA } from '../../js/ui/pantalla-ayuda.js'

beforeEach(() => {
  const dom = new JSDOM('<div id="raiz"></div>')
  globalThis.document = dom.window.document
})

describe('ayuda del gestor institucional', () => {
  it('conserva trazabilidad explícita a las dos transcripciones', () => {
    const fuentes = new Set(PREGUNTAS_AYUDA.map((item) => item.fuente))
    expect(fuentes).toContain('Audio 1')
    expect(fuentes).toContain('Audio 2')
  })
  it('encuentra respuestas sin depender de tildes', () => {
    expect(filtrarPreguntas('contenidos de ejemplo').map((item) => item.pregunta)).toContain('¿Por qué aparecen contenidos de ejemplo en el sitio de prueba?')
    expect(filtrarPreguntas('notificacion').map((item) => item.pregunta)).toContain('¿Dónde veo las notificaciones de tareas?')
    expect(filtrarPreguntas('Canva')).toHaveLength(2)
    expect(filtrarPreguntas('Pegar enlace').map((item) => item.pregunta)).toContain('¿Cómo agrego un enlace de Google Drive o Canva a la Biblioteca?')
    expect(filtrarPreguntas('recurrente').map((item) => item.pregunta)).toContain('¿Cómo agendo una actividad recurrente?')
    expect(filtrarPreguntas('reunión recurrente').map((item) => item.pregunta)).toContain('¿Cómo agendo una reunión recurrente?')
    expect(filtrarPreguntas('tarea recurrente').map((item) => item.pregunta)).toContain('¿Cuándo uso una tarea recurrente en lugar de una actividad recurrente?')
    expect(filtrarPreguntas('esfuerzo estimado').map((item) => item.pregunta)).toContain('¿Qué significa esfuerzo estimado?')
    expect(filtrarPreguntas('programa').map((item) => item.pregunta)).toContain('¿Qué es el programa de un proyecto?')
    expect(filtrarPreguntas('persona archivada').map((item) => item.pregunta)).toContain('¿Qué pasa con una persona archivada en el reporte mensual?')
    expect(filtrarPreguntas('League Gothic').map((item) => item.pregunta)).toContain('¿Puedo usar League Gothic en una pieza?')
    expect(filtrarPreguntas('Drive').map((item) => item.pregunta)).toContain('¿Cómo agrego una fotografía a una pieza?')
    expect(filtrarPreguntas('carrusel').map((item) => item.pregunta)).toContain('¿Cómo creo una imagen para redes o una campaña?')
    expect(filtrarPreguntas('página pública').map((item) => item.pregunta)).toContain('¿Guardar un borrador cambia la página pública?')
    expect(filtrarPreguntas('pantalla desordenada').map((item) => item.pregunta)).toContain('¿Qué hago si veo una pantalla desordenada después de una actualización?')
    expect(filtrarPreguntas('más grande el título').map((item) => item.pregunta)).toContain('¿Cómo hago más grande el título de una pieza?')
    expect(filtrarPreguntas('publicación de la página web').map((item) => item.pregunta)).toContain('¿Una publicación de la página web cuenta como actualización del gestor?')
    expect(filtrarPreguntas('vista previa puede verse distinta').map((item) => item.pregunta)).toContain('¿Por qué la vista previa puede verse distinta de prueba.aletea.org?')
    expect(filtrarPreguntas('carta membretada').map((item) => item.pregunta)).toContain('¿Cómo creo una carta membretada?')
    expect(filtrarPreguntas('hoja blanca').map((item) => item.pregunta)).toContain('¿Cómo creo una carta membretada?')
    expect(filtrarPreguntas('firma').map((item) => item.pregunta)).toContain('¿Cómo agrego una firma y guardo la carta como PDF?')
    expect(filtrarPreguntas('reducir una foto').map((item) => item.pregunta)).toContain('¿Tengo que reducir una foto antes de agregarla al perfil?')
    expect(filtrarPreguntas('estado de cuenta mensual').map((item) => item.pregunta)).toContain('¿Qué muestra el estado de cuenta mensual?')
    expect(filtrarPreguntas('cierre mensual').map((item) => item.pregunta)).toContain('¿Cómo interpreto el cierre mensual de Fútbol sin Barreras?')
    expect(filtrarPreguntas('compromiso').map((item) => item.pregunta)).toContain('¿Un compromiso de pago cambia el saldo?')
    expect(filtrarPreguntas('recordatorios de pago').map((item) => item.pregunta)).toContain('¿El gestor envía recordatorios de pago?')
    expect(filtrarPreguntas('enlaces del gestor').map((item) => item.pregunta)).toContain('¿Por qué los enlaces del gestor ahora tienen nombres como /finanzas o /agenda?')
    expect(filtrarPreguntas('información aparece al compartir').map((item) => item.pregunta)).toContain('¿Qué información aparece al compartir un enlace del gestor?')
    expect(filtrarPreguntas('mes control externo').map((item) => item.pregunta)).toContain('¿Cómo guardo un control externo del mes?')
    expect(filtrarPreguntas('beca grupo').map((item) => item.pregunta)).toContain('¿Cómo cambio el grupo, la beca o el tipo de cuota?')
    expect(filtrarPreguntas('sirve un botón').map((item) => item.pregunta)).toContain('¿Cómo sé para qué sirve un botón?')
    expect(filtrarPreguntas('activar vincular').map((item) => item.pregunta)).toContain('¿Cómo se administra un formulario que aparecerá en la página?')
    expect(filtrarPreguntas('aviso de reposición').map((item) => item.pregunta)).toContain('¿Por qué un formulario ya muestra una actividad, formación o producto?')
    expect(filtrarPreguntas('borrar participante').map((item) => item.pregunta)).toContain('¿Cómo archivo o recupero a una persona sin perder su historial?')
    expect(filtrarPreguntas('calendario').map((item) => item.pregunta)).toContain('¿Cómo creo una actividad o una reunión en la agenda?')
    expect(filtrarPreguntas('login usuario').map((item) => item.pregunta)).toContain('¿Cuál es la diferencia entre una persona y una cuenta de acceso?')
  })

  it('abre con recorridos breves y navega a la pantalla indicada', () => {
    const alIrA = vi.fn()
    const raiz = document.getElementById('raiz')
    crearPantallaAyuda(raiz, { alIrA, admin: true })
    expect(raiz.querySelectorAll('.ayuda-pregunta')).toHaveLength(5)
    expect(raiz.querySelectorAll('.ayuda-atajo')).toHaveLength(6)
    ;[...raiz.querySelectorAll('.ayuda-categoria-filtro')].find((control) => control.querySelector('span')?.textContent === 'Equipos').click()
    const control = [...raiz.querySelectorAll('a')].find((enlace) => enlace.textContent.includes('Abrir Áreas'))
    control.click()
    expect(alIrA).toHaveBeenCalledWith('cms-areas')
  })

  it('abre un formulario público como enlace real sin interceptar una pestaña nueva', () => {
    const raiz = document.getElementById('raiz')
    crearPantallaAyuda(raiz, { busquedaInicial: 'como pruebo los formularios del sitio nuevo' })
    const enlace = raiz.querySelector('a[href="https://prueba.aletea.org/contacto/"]')
    expect(enlace).not.toBeNull()
    expect(enlace.textContent).toContain('Probar formularios')
  })

  it('muestra todos los temas sin desplazamiento horizontal y permite filtrar una categoria', () => {
    const raiz = document.getElementById('raiz')
    crearPantallaAyuda(raiz, { admin: true })
    expect(raiz.querySelector('[aria-label="Elegir tema de ayuda"]')).not.toBeNull()
    expect([...raiz.querySelectorAll('.ayuda-categoria-filtro')].map((control) => control.querySelector('span')?.textContent)).toContain('Equipos')
    const filtro = [...raiz.querySelectorAll('.ayuda-categoria-filtro')].find((control) => control.querySelector('span')?.textContent === 'Notificaciones')
    filtro.click()
    expect(raiz.querySelectorAll('.ayuda-pregunta')).toHaveLength(7)
    expect(raiz.textContent).toContain('¿El teléfono avisa automáticamente')
    expect(raiz.textContent).toContain('¿Cómo reemplazamos los avisos cotidianos de WhatsApp?')
  })

  it('oculta las instrucciones administrativas a cuentas sin ese perfil', () => {
    const raiz = document.getElementById('raiz')
    crearPantallaAyuda(raiz)
    expect(raiz.textContent).not.toContain('Revisar accesos')
    expect(raiz.textContent).toContain('¿Qué hago cuando una sección dice que me falta acceso?')
    expect(filtrarPreguntas('solicitud eliminación datos').some((item) => item.soloAdmin)).toBe(true)
  })

  it('explica finanzas sin presentar un compromiso como pago ni un recordatorio como envio', () => {
    const raiz = document.getElementById('raiz')
    crearPantallaAyuda(raiz, { admin: true })
    const filtro = [...raiz.querySelectorAll('.ayuda-categoria-filtro')].find((control) => control.querySelector('span')?.textContent === 'Finanzas')
    filtro.click()
    expect(raiz.querySelectorAll('.ayuda-pregunta')).toHaveLength(14)
    expect(raiz.textContent).toContain('sin usar el Excel')
    expect(raiz.textContent).toContain('qué requisito está cumplido')
    expect(raiz.textContent).toContain('una sola vez el 10 por ciento')
    expect(raiz.textContent).toContain('vuelve automáticamente a la revisión')
    expect(raiz.textContent).toContain('¿Cómo elimino un participante que agregué para probar?')
    expect(raiz.textContent).toContain('conserva su ficha, pagos e historial')
    expect(raiz.textContent).toContain('Inscripción')
    expect(raiz.textContent).toContain('Exportar mes')
    expect(raiz.textContent).toContain('descuento se aplica automáticamente')
    expect(raiz.textContent).toContain('no crea un cargo ni cuenta como pago')
    expect(raiz.textContent).toContain('no guarda el texto ni lo envía automáticamente')
  })

  it('explica el ingreso futuro y cómo colapsar el radar', () => {
    const raiz = document.getElementById('raiz')
    crearPantallaAyuda(raiz, { admin: true, busquedaInicial: 'fecha futura' })
    expect(raiz.textContent).toContain('En la organización desde admite una fecha futura')
    crearPantallaAyuda(raiz, { admin: true, busquedaInicial: 'Radar institucional' })
    expect(raiz.textContent).toContain('Usá Ocultar')
    expect(raiz.textContent).toContain('recuerda esta preferencia')
  })

  it('abre una búsqueda compartida y permite copiar su enlace', async () => {
    const alCopiarEnlace = vi.fn(async () => {})
    const raiz = document.getElementById('raiz')
    crearPantallaAyuda(raiz, { busquedaInicial: 'Canva', alCopiarEnlace })
    expect(raiz.querySelector('[aria-label="Buscar en la ayuda"]').value).toBe('Canva')
    expect(raiz.querySelectorAll('.ayuda-pregunta')).toHaveLength(2)
    expect(raiz.querySelector('.ayuda-pregunta').open).toBe(false)
    ;[...raiz.querySelectorAll('button')].find((control) => control.textContent === 'Copiar esta búsqueda').click()
    await Promise.resolve()
    expect(alCopiarEnlace).toHaveBeenCalledWith('Canva')
    expect(raiz.textContent).toContain('Enlace a esta búsqueda copiado')
  })

  it('no muestra versiones técnicas y permite copiar una respuesta', async () => {
    const alCopiarEnlace = vi.fn(async () => {})
    const alCopiarTexto = vi.fn(async () => {})
    const raiz = document.getElementById('raiz')
    crearPantallaAyuda(raiz, { admin: true, busquedaInicial: 'sin perder su historial', alCopiarEnlace, alCopiarTexto })
    expect(raiz.querySelector('.ayuda-fuente')).toBeNull()
    expect(raiz.querySelector('.ayuda-pregunta').open).toBe(true)
    ;[...raiz.querySelectorAll('button')].find((control) => control.textContent === 'Copiar pasos').click()
    await Promise.resolve()
    expect(alCopiarTexto).toHaveBeenCalledWith(expect.stringContaining('sin perder su historial'))
    expect(raiz.textContent).toContain('También puede ayudarte')
  })

  it('retira instrucciones internas que ya no ayudan a completar tareas', () => {
    const preguntas = PREGUNTAS_AYUDA.map((item) => item.pregunta)
    expect(new Set(preguntas).size).toBe(preguntas.length)
    expect(preguntas).not.toContain('¿La etapa de corto plazo necesita una validación presencial?')
    expect(preguntas).not.toContain('¿Cómo vuelvo rápidamente a una sección que estaba usando?')
  })
})
